#!/bin/bash

###########################      About this script      ##########################
#                                                                                #
#   Purpose:                                                                     #
#            Loads the LaunchAgent for auto-erase-install-runner                 #
#                                                                                #
#   Created by Mart Verburg                                                      #
#               March 2021                                                       #
#                                                                                #
#   Version history                                                              #
#                                                                                #
#                                                                                #
#                                                                                #
#   Instructions                                                                 #
#            run automatically by installer when installing package              #                                                       #
#                                                                                #
##################################################################################

# unload any previous version that may have been around, particularly during testing ;-)
launchctl unload /Library/LaunchDaemons/no.datamind.auto-erase-install-runner.plist
launchctl load -w /Library/LaunchDaemons/no.datamind.auto-erase-install-runner.plist


